name = "DMCC"
license = "MIT"
licenselink = "https://github.com/yourusername/hugo-theme-dmcc/blob/main/LICENSE"
description = "A minimal, elegant Hugo theme with blue accents and featured posts"
homepage = "https://github.com/yourusername/hugo-theme-dmcc"
tags = ["blog", "minimal", "clean", "responsive", "blue", "featured-posts"]
features = ["responsive", "featured-posts", "callouts", "navigation", "rss"]
min_version = "0.121.1"

[author]
  name = "Danny McClelland"
  homepage = "https://blog.dmcc.io"
